#pragma once

#define NO_DEBUG
#define NO_PRINT
#define NO_USB_STARTUP_CHECK

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 8
#define MOUSEKEY_TIME_TO_MAX 64
#define MOUSEKEY_MAX_SPEED 40
#define MOUSEKEY_FRICTION 1
#define MOUSEKEY_MOVE_DELTA 1

// #define UNICODE_SELECTED_MODES UNICODE_MODE_MACOS, UNICODE_MODE_WINCOMPOSE, UNICODE_MODE_LINUX
// #define UNICODE_KEY_MAC KC_LALT
// #define UNICODE_KEY_LNX LCTL(LSFT(KC_U))
// #define UNICODE_KEY_WINC KC_RALT
// #define UNICODE_SELECTED_MODES -1
// #define UNICODE_CYCLE_PERSIST true
// #define UNICODE_TYPE_DELAY 10

#ifdef AUDIO_ENABLE
#    define STARTUP_SONG SONG(S__NOTE(_E2))
#    define GOODBYE_SONG SONG(S__NOTE(_C2))
#    define AUDIO_PIN A9
#    define AUDIO_PWM_DRIVER PWMD1
#    define AUDIO_PWM_CHANNEL 1
#    define AUDIO_PWM_COMPLEMENTARY_OUTPUT
#endif

// for sanwa keyboard emulation KVM
#undef NKRO_ENABLE

#define USB_POLLING_INTERVAL_MS 5

#define DEBOUNCE 10
