#pragma once

#define VENDOR_ID 0x3434
#define PRODUCT_ID 0x0320
#define DEVICE_VER 0x0100

// #define NO_DEBUG
// #define NO_PRINT
// #define NO_USB_STARTUP_CHECK
#define RGB_MATRIX_SLEEP

#ifdef VIA_ENABLE
#    define VIA_QMK_RGBLIGHT_ENABLE
#endif

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_TIME_TO_MAX 80
#define MOUSEKEY_MAX_SPEED 5
#define MOUSEKEY_FRICTION 50
#define MOUSEKEY_MOVE_DELTA 1

#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_MACOS, UNICODE_MODE_WINCOMPOSE
#define UNICODE_KEY_MAC KC_LALT
#define UNICODE_KEY_LNX LCTL(LSFT(KC_U))
#define UNICODE_KEY_WINC KC_RALT
#define UNICODE_CYCLE_PERSIST true
#define UNICODE_TYPE_DELAY 0

#ifdef AUDIO_ENABLE
#    undef AUDIO_PIN
#    define AUDIO_PIN A5
#    define STARTUP_SONG SONG(S__NOTE(_E2))
#    define GOODBYE_SONG SONG(S__NOTE(_C2))
#endif

// #define AUDIO_ALT_PIN A5
// #define AUDIO_PIN_ALT_AS_NEGATIVE
// #define AUDIO_PWM_DRIVER PWMD1
// #define AUDIO_PWM_CHANNEL 1
// #define AUDIO_STATE_TIMER GPTD9
// #define AUDIO_PWM_COMPLEMENTARY_OUTPUT

// for sanwa keyboard emulation KVM
#undef NKRO_ENABLE

#define USB_POLLING_INTERVAL_MS 5

#define DEBOUNCE 10
